OP-TEE/optee_docs

building/devices/qemu.rst
Add instructions that describes how to debug TEE core using GDB together
with QEMU.
=> qemu: add instructions telling how to debug TEE core

architecture/core.rst
```
Remove deprecated references to Linux driver resources. This
prevents dependency on Linux OP-TEE driver evolution and opens
perspective to alternate non-secure clients as U-Boot.
Fix Joakim TODO tag on deprecated bootcfg_get_memory().
Add description of the dynamic shared memory: registration/discovery
from secure world and buffer registration by non-secure world.
```
While exploring the new docs, found some untrue statement and deprecated info (incl @jbech-linaro todo tag). This is an attempt to clean the Shared Memory description part while not adding to much info that could deprecate.
=> archi/core: correct shared memory and add dynamic shm

general/platforms.rst
Signed-off-by: Sahil Malhotra <sahil.malhotra@nxp.com>
=> platform: add ls1028ardb links

building/aosp/aosp.rst
=> aosp.rst: update doc to reflect current dev env

general/platforms.rst
Information added in this patch is taken from corresponding patch in
OP-TEE/optee_os, commit ID: 42615b81f3f7.
@OP-TEE/plat-imx: please help to confirm validity of information added as part of this patch.
=> platform: Add i.MX8M links

architecture/secure_storage.rst
replaced link to old .md file with internal link in .rst
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
=> fix broken link for RPMB secure storage

building/aosp/aosp.rst
=> aosp: add optional tag info for git clone

building/prerequisites.rst
=> prerequisites: list both python 2 and 3 packages

building/trusted_applications.rst
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
=> Fix some simple typos in TA documentation.

architecture/trusted_applications.rst
Adds a description of the TA database.
=> Update "Secure Storage TA" section with tadb

general/releases.rst
A couple of fixes to the release procedure for minor issues that I noticed when doing 3.8.0.
=> Release fixes

building/prerequisites.rst
Signed-off-by: Christina Quast <contact@christina-quast.de>
=> Add python3-pycryptodome to requirements

building/gits/optee_test.rst, general/coding_standards.rst
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
=> Mention make targets for checkpatch in documentation.

architecture/secure_storage.rst
See [old PR](https://github.com/OP-TEE/optee_docs/pull/63).
=> secure_storage: Fix tiny grammatical error.

building/gits/optee_os.rst
Describe the import/* branches in the optee_os Git.
=> Document import branches in optee_os.git

architecture/trusted_applications.rst
Document support for:
- Optionally encrypted REE-FS TAs.
- Rollback protection of REE-FS TAs.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
=> arch/tas: Updates for REE filesystem TAs

general/releases.rst
Starting from v3.10.0 add a table showing old, upcoming and future
releases.
=> release: add release schedule

building/trusted_applications.rst
Update the instructions for offline signing to reflect the name
change of the signing script and the switch from PKCS#1.5 to PSS
as preferred RSA padding mode.
Signed-off-by: Markus S. Wamser <github-dev@mail2013.wamser.eu>
=> building: update offline signing doc

general/platforms.rst
Update the platform list to include the Renesas RZ/G platform.
Signed-off-by: Lad Prabhakar <prabhakar.mahadev-lad.rj@bp.renesas.com>
=> platform: Add newly added Renesas RZ/G platform

architecture/globalplatform_api.rst
This patch adds a small description of the design of
the plugin framework and shows APIs can be used for work with it.
Signed-off-by: Aleksandr Anisimov <a.anisimov@omprussia.ru>
=> api extensions: loadable plugin framework description

architecture/secure_boot.rst
Add a note stating TF-A implementation supports Armv7-A platforms.
=> architecture: boot: mention TF-A does support Armv7-A

building/devices/stm32mp1.rst
Update the word 'Board' to correct spelling.
Suggested-by: Santeri Paavolainen <santtu@iki.fi>
=> devices: fix typo in STM32MP1

faq/faq.rst
Describe where the latest Linux driver code is found and how to
determine which kernel version contains which commit.
=> faq: add entry about kernel versions

.readthedocs.yaml, requirements.txt
This is meant to address the issues seen on readthedocs after applying #118 .
=> Add requirements file and readthedocs yaml file

architecture/core.rst
Updates the MMU section to cover long-descriptor translation tables in a
subsection.
=> architecture: core: update mmu section

architecture/core.rst
Describes notifications, both synchronous and asynchronous.
Documentation relating to https://github.com/OP-TEE/optee_os/pull/4601 and https://github.com/linaro-swg/linux/pull/93
=> architecture: core: add a section on notifications

architecture/core.rst
Adds a section with a few diagrams describing how memory is shared with
secure world both with SMC and FF-A based communication.
=> architecture: core: add a section on registration of shared memory

architecture/secure_storage.rst
Document how platforms can control the conditions for allowing the RPMB key
to be programmed.
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
=> secure_storage: RPMB platform access

.readthedocs.yaml, building/prerequisites.rst, conf.py, requirements.txt
* update the prerequisites
* add support for sphinx-tabs
* fix language warning
=> Prerequisites updates, Ubuntu 22.04, 20.04 and older + some config changes.

architecture/spmc.rst
Recently a new mechanism was introduced to the optee_os SPMC component, which enables loading SP packages generated by TF-A and loaded from the FIP. Update the documentation to reflect these changes.
=> architecture: spmc: document SP loading mechanisms

architecture/index.rst, architecture/subkeys.rst, architecture/trusted_applications.rst
Adds a new section on subkeys and a note on subkeys with REE-FS TAs.
=> architecture: describe subkeys

building/devices/index.rst, building/devices/rockpi4.rst, building/gits/build.rst, building/prerequisites.rst
Adds build instructions for Radxa ROCK Pi 4 boards.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> Add documentation for ROCK Pi 4

architecture/spmc.rst
A new raw binary format was introduced to have a common secure partition format across different SPMC implementations. Add documentation about the format and its load process.
The PR that introduces the feature to optee_os is available here: https://github.com/OP-TEE/optee_os/pull/5794
=> architecture: spmc: document raw binary format SPs

architecture/trusted_applications.rst, conf.py, debug/benchmark.rst, faq/faq.rst, requirements.txt
This adds the missing configuration to be able to render #186 . Since I was doing documentation changes I took the opportunity to also fix some existing warnings and errors.
=> Sphinx panels

architecture/spmc.rst
Add detailed description about the level of support of manifest fields and FF-A interfaces along listing the limitations.
=> architecture: spmc: document FF-A compliance

conf.py
=> config: extend Copyright date

debug/ftrace.rst
The ftrace implementation has changed [1]. Update the documentation accordingly.
Link: https://github.com/OP-TEE/optee_os/commit/5c2c0fb31efb [1]
=> ftrace: update after introduction of ftrace_format.py

architecture/core.rst
Detail a bit contiguous/reserved and dynamic shared memory are and highlight the latter is preferred on supported platforms.
Describe a bit more dynamic shared memory constraints and give pointers for secure core configuration (DT node name and `register_ddr()` macro).
=> architecture: core: detail reserved/dynamic shared memory

building/trusted_applications.rst
Describe a bit TEE login methods OP-TEE implements and how a TA can sue it.
I've created this change based on https://github.com/OP-TEE/optee_os/issues/6436.
=> building: trusted applications: get client identity

building/trusted_applications.rst
The pkcs11-tool approach had issues and is exchanged with the openssl command for conformity.
=> building: Exchange TA HSM signing step with openssl command

architecture/secure_storage.rst
Describe the preferred way of programming the RPMB key and add risks of automatic programming from OP-TEE.
=> secure_storage: preferred way of programming RPMB key

building/userland_integration.rst
=> Use key id as --id instead of key label

general/platforms.rst
Add the Telechips TCC805x Platform
Reference board:
https://topst.ai/product/topstD3
=> platform: add Telechips TCC805x

building/devices/rpi3.rst
Reflect the current way we produce the Raspberry Pi 3B build image, which now has two partitions instead of a single tar archive. The instructions have been updated to extract the root filesystem from the image itself when preparing the NFS share.
Also, update `/etc/exports` with more permissive settings and change the exported IP range to `192.168.0.x` instead of `192.168.1.x`.
=> rpi3: update NFS instructions

general/contact.rst
Replace the outdated IRC section with a new Discord section.
=> contact: replace IRC with discord
