general/platforms.rst
Update bcm-ns3 to the platform supported list.
Signed-off-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com>
=> plat-bcm: add broadcom ns3 platform support.

architecture/device_tree.rst
```
archi/device-tree: correct deprecated info and add overlay
Reorganize a bit documentation to clarify the core DT API and
how generic boot uses the 2 supported DTB types (external & embedded).
Document CFG_EXTERNAL_DTB_OVERLAY.
```
While exploring the new docs, found some untrue statement and deprecated info (incl @jbech-linaro todo tag). This is an attempt to clean the DT description part while not adding to much info that could deprecate.
=> archi/device-tree: correct deprecated info and add overlay

architecture/trusted_applications.rst
`TA_FLAG_EXEC_DDR` and `TA_FLAG_REMAP_SUPPORT` are not supported by OP-TEE and deprecated since a while. This change updates the documentation accordingly.
=> arch: update deprecated TA flags EXEC_DDR and REMAP_SUPPORT

architecture/globalplatform_api.rst, architecture/trusted_applications.rst, building/toolchains.rst
minor fixes in `architecture/trusted_applications.rst` and `build/toolchains.rst`.
* Replace `===` underlines with `---` underlines for subsection parts.
* Remove section/subsection numbering.
* Move local references to end of .rst file.
=> Fixes related to section syntax

general/coding_standards.rst
Clarify how variables are initialized in different gits.
=> coding_standard: clarify initialization

building/devices/index.rst, building/devices/zynqmp.rst
This commit adds the required documentation describing the use of the zynqmp.mk
makefile from 'build' repository.
=> Add documentation for Xilinx zcu102, zcu104 and zcu106 ZynqMP boards

architecture/core.rst
Adds the configuration flags CFG_CORE_DYN_SHM and CFG_CORE_RESERVED_SHM
in the shared memory section.
=> Shared memory configuration flags

building/devices/qemu.rst
A more recent toolchain will now be used when setting up a full OP-TEE
developer build, therefore we are removing the parts in the hint that
mentioned a GDB build where TUI mode wasn't enabled.
=> qemu/gdb: update the hint about running gdb in TUI mode

.travis.yml, Makefile
Since I haven't been able to find an equivalent to GCC's "``Wall` `Werror`" when building Sphinx documentation I came up with this, which is a poor mans solution to force a Travis build error when warnings are shown when building the Sphinx documentation. With this, Travis sanity builds will show up with an error in the pull request instead of shown as a successful build (which isn't really correct).
I've done some tests, one where I force an error, then we [get this result](https://travis-ci.org/jbech-linaro/optee_docs/jobs/541649386) and when there are no errors it looks like [this](https://travis-ci.org/jbech-linaro/optee_docs/jobs/541652957).
=> travis: Force Travis to show failure on pull requests

building/devices/devbox.rst, building/devices/index.rst, building/gits/build.rst
This adds a DeveloperBox device-specific document, and updates
build.git and manifest.git support table. 
The manifest for DeveloperBox is pending at [manifest.git PR](https://github.com/OP-TEE/manifest/pull/139).
=> Add documentation for DeveloperBox

debug/ftrace.rst, debug/gprof.rst, debug/index.rst
Add ftrace user guide for function tracing of user Trusted Applications
and corresponding user libraries.
Depends on https://github.com/OP-TEE/optee_os/pull/2912 and https://github.com/OP-TEE/optee_client/pull/155.
=> debug: add usage guide for function tracing of user TAs

general/platforms.rst
The link to the stm32mp1 was missing the ending underscore, hence the
link wasn't rendered correctly.
=> platforms: fix broken link to stm32mp1 external page

building/prerequisites.rst
Adds the packages ccache and python-pyelftools to prerequisites.
=> Add ccache and python-pyelftools to prerequisites

debug/ftrace.rst
Add typical ouput for a function graph especially explaining duration
column displayed in the ouput function graph.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
=> ftrace: Add typical function graph reference output

architecture/trusted_applications.rst
optee_os commit 5843bb755f15 ("core: move PTAs from core/arch/arm/pta
to core/pta") has moved the Pseudo-TA source file stats.c. Update the
documentation accordingly.
Link: https://github.com/OP-TEE/optee_os/commit/5843bb755f15
=> Update Pseudo-TA path

general/index.rst, general/releases.rst
Add page that contains some general information about OP-TEE releases.
Information like release cadence, changelog, versioning schema and a
checklist for doing releases can be found there.
@jforissier your feedback if any is most appreciated here.
// Joakim
=> Add documentation page covering releases and release related work

building/devices/index.rst, building/devices/zynqmp.rst
ZynqMP documentation updated to reflect changes introduced by the new support
of Ultra96 boards (see PR https://github.com/OP-TEE/build/pull/380).
=> Update ZynqMP documentation

general/releases.rst
CFG_OPTEE_REVISION_MINOR and sometimes CFG_OPTEE_REVISION_MAJOR need
to be incremented for a release. Mention it in the documenation.
=> releases: add step about incrementing revision in mk/config.mk

debug/ftrace.rst
Update doc with recently added configuration option: CFG_SYSCALL_FTRACE=y.
Also, rename CFG_TA_FTRACE_SUPPORT to CFG_FTRACE_SUPPORT.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
=> ftrace: Update doc with new CFG_SYSCALL_FTRACE=y option

architecture/secure_boot.rst
The TF-A repository restructured its documentation with subfolders,
change the links accordingly.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>
=> architecture: update secure boot links

building/index.rst, faq/faq.rst
The quick QEMU build instructions are in the FAQ and are not linked from
the "Build and run" page. Therefore they are a bit difficult to find.
This commit adds a link.
=> Link to QEMU build commands in the FAQ from the "Build an run" page

general/releases.rst
The get_maintainer.py script now has an option to show the email
addresses to be used when sending release announcements. Document it.
=> releases: update command to get email addresses

building/gits/optee_os.rst, building/toolchains.rst
Add instructions on how to build optee_os using llvm/clang.
=> toolchain: add llvm/clang instructions

building/aosp/aosp.rst
Fix link to the Prerequisites page.
=> aosp: fix broken link

architecture/trusted_applications.rst
It seems people get confused in what a pseudo TA is. This change
emphases the nature of pseudo TAs in the documentation: a pseudo
TA is an interface, no more.
=> pseudo TA: clarify what is a pseudo TA

building/devices/index.rst, building/devices/stm32mp1.rst, building/gits/build.rst
Describe how to build a bootable image file embedding OP-TEE in some
STM32MP1 base boards, namely STM32MP157C-DK2 and STM32MP157C-EV1.
The documentation provides link to the hardware description of the
boards.
=> stm32mp1: initial support

building/gits/optee_os.rst, debug/ftrace.rst, debug/gprof.rst
libmpa was removed from optee_os so it should not be referenced anymore.
=> Remove references to libmpa

architecture/libraries.rst
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
=> Fix typo in libmpa deprecation note

building/gits/optee_os.rst, building/toolchains.rst
Add instructions to download the llvm/clang toolchain as an alternative
to doing a manual build.
=> llvm/clang: add instructions to download toolchain

general/releases.rst
Following https://github.com/OP-TEE/manifest/pull/163, the Linux
repository needs to have a release tag too.
=> releases: tag linux.git too

architecture/core.rst
OP-TEE can work with only dynamic (noncontiguous) shared memory. Fix
the description and explain that libteec uses the dynamic memory when
available.
=> core: contiguous shared memory pool is not mandatory

faq/faq.rst
Fixes the spelling of "Pseudo TA".
=> faq: fix spelling mistakes (psuedo)

building/gits/optee_os.rst
Adds a section to explain the purpose and usage of the 'force' macro
in optee_os configuration makefiles.
=> Document the force macro

building/gits/optee_test.rst
Starting from OP-TEE v3.11.0, the OP-TEE gits have been updated to work
with the "TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z"
version of the GlobalPlatform Compliance Test suite. Update the
instructions to reflect the changes.
=> optee_test: update instructions for the extended tests

building/prerequisites.rst
The i386 packages mentioned in the list of prerequisites for building
OP-TEE are not needed anymore (as far as I can recall, they were used
by older GCC toolchains) and have been obsoleted in the latest Ubuntu
distributions, causing error messages when trying to install.
Therefore, remove them.
=> Remove i386 packages from build prerequisites

general/presentations.rst
Linaro had to make the change because "s3.amazonaws.com" is the old way
of reaching a S3 bucket and Amazon are turning it off.
=> presentations: update links to the new location

general/presentations.rst
Update the presentation page with three relevant presentations from the
LVC20 Linaro Connect.
- LVC20-112 - PSA Secure Partitions in OP-TEE
- LVC20-118 - SCMI server in TEE
- LVC20-204 - Encrypted firmwares and how to bake them right
=> presentations: add links to LVC20 presentations

building/index.rst
Reorder table of content to have the follow natural flow:
- prerequisites
- device specific
- AOSP specific
- other articles...
**(edited: move back toolchain articles to "other articles...")**
=> index: reorder table of content to start from the prerequisites

building/devices/qemu.rst
Add an explicit example of shell commands to get, build and run
OP-TEE on Qemu (v7 and v8). This is quite helpful for one reading
the documentation to easy copy/paste required commands, rather than
digging back in generic build instruction to setup the right
command series.
=> building: qemu: add fetch/build/run commands example

building/gits/build.rst, building/gits/build_legacy.rst, building/gits/index.rst
Move pre 3.1.0 stable release specific instruction to a separated
article to simplify the content build.rst when one follows build
instructions.
=> building: move pre-v3.1 info to another article

building/efi_vars/stmm.rst
We propose using RPMB_WRITE_KEY=y, which might end up writing a default
key. So add an explicit warning and a link to caveats
Acked-by: Jerome Forissier <jerome@forissier.org>
Signed-off-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
=> building: standalonemm: Add explicit warning regarding RPMB keys

general/coding_standards.rst
Optee_client package expects { 0 } as universal initializer. See
rational from [1].
Link: [1] https://github.com/OP-TEE/optee_client/pull/230#issuecomment-721011505
=> coding standard: add optee_client clause on { 0 } initializer

.github/workflows/stales.yml
Just as for the other OP-TEE gits, let's enable the GitHub
actions/workflow bot on optee_docs as well. Doing so will help us clean
stale issues and pull requests.
=> github: add and enable actions/workflow

general/coding_standards.rst
```
Misra C rule 7.2 says:
"A 'u' or 'U' suffix shall be applied to all integer constants that are
represented in an unsigned type"
Besides Misra this makes sense anyway to make the sign and size of the
integer well defined instead of depending on the size of the constant or
version of C standard a compiler is using.
Do this with the U() macro instead of an explicit 'U' at the end to make
the defines usable from assembly too.
```
This is a step at trying to align more with Misra C recommendations.
There's quite a few recommendations to contemplate, with some quite intrusive or perhaps even ill suited for OP-TEE. 
But this recommendation (rule 7.2) isn't too bad and a is a good start.
Given how many rules there are we can't list …
=> coding standard: defining unsigned integer constants using U()

architecture/index.rst, architecture/spmc.rst
Add documentation for the following SPMC features:
-Handling FF-A messages
-SP initialisation and start
-Rxtx buffers
Signed-off-by: Jelle Sels <jelle.sels@arm.com>
=> SPM: Add SPMC documentation

building/prerequisites.rst
Recent versions of QEMU needs ninja-build when building, so add that
to prerequisites.
=> Add ninja-build to prerequisites

debug/abort_dumps.rst
The target usually doesn't have the tools required by symbolize.py
(Python interpreter, binutils tools...) nor the original ELF files.
This script is meant to be run on the host in the build environment.
=> debug: clarify that symbolize.py is to be run on the host

building/prerequisites.rst
1) ubuntu 18.04: apt install python3-pycryptodome == 3.4.7 as
pycryptodomex on ubuntu and has the highest priority to be `import`.
2) The pycryptodomex 3.4.7 is not supported by sign_encrypt.py.
3) Need to remove python3-pycryptodome and install the newest
pycryptodome by pip install tool.
=> [prerequisites] add note about <= ubuntu 18.04

building/gits/build.rst, building/gits/build_legacy_3_1_0-3_8_0.rst, building/gits/index.rst
Versions 3.1.0 to 3.8.0 are known to cause issues when cloning with a
version of the repo tool >= v2.0.0. Document this fact and provide a
workaround.
=> building: add section about building stable 3.1.0 to 3.8.0

faq/faq.rst
Add link to Android APK reference implementation of the Hello World TA
example.
=> faq: add link to Android APK ref implementation

building/devices/stm32mp1.rst
Remove the sudo command from the shell instruction . When things
can be made without sudo admin rights, it is really preferred to
use standard rights hence not recommending this in this documentation.
The fact is it may not be necessary to use sudo right to update
an SDcard device on a host, depending on the host configuration.
=> stm32mp1: remove sudo command when loading SDcard image

faq/faq.rst
Updates the "How are you testing OP-TEE?" entry with a Azure link,
replacing the old Travis and Shippable links.
Reported-by: Mike Holmes <mike.holmes@linaro.org>
=> faq: replace Travis and Shippable with Azure DevOps pipelines

architecture/globalplatform_api.rst
TEE Internal API extensions are declared in two header files for TAs to
use: <tee_api_defines_extensions.h> and <tee_internal_api_extensions.h>.
The former contains macro definitions, the latter declares new functions
and also includes the other one. While it may be enough for a TA to
include only the former (for key derivation extensions in particular),
for simplicity let's document only <tee_internal_api_extensions.h>.
=> api extensions: main header file is <tee_internal_api_extensions.h>

architecture/porting_guidelines.rst, general/contact.rst
We have recently had a couple of security incidents being reported to
the OP-TEE project. With these reports it's clear that there is a need
to clarify the role of the OP-TEE project as well as adding some extra
pointers to the vulnerability reporting.
All in all it boils down to that the OP-TEE project serves as a
reference implementation for developers and device manufacturers. A
consequence of using a reference implementation is that the one using it
in end products must understand that there are certain changes that
needs to be done for the final product. These changes are not always
available nor applicable in the vanilla and default OP-TEE reference
implementation.
It is important to understand that for two reasons. First is to make
sure that the end product is configured to be …
=> Incident reporting: clarify the role of the OP-TEE project

architecture/index.rst, architecture/platforms/index.rst, architecture/platforms/nxp.rst, architecture/porting_guidelines.rst
Hello @jbech-linaro @ruchi393 @jenswi-linaro @jforissier 
In this pull-request:
- I added a dedicated space for platform specific documentation. Please let me know if you have a something else in mind regarding the doc structure.
- I added the NXP security disclaimer to the NXP page.
Note: I had to force `docutils<0.18` in `requirements.txt` because of this issue : https://github.com/readthedocs/readthedocs.org/issues/8618. Let me know if you want me to merge this (temporary) fix.
Thanks!
Clement
=> Add NXP security disclaimer

building/prerequisites.rst
Building Qemu with VirtFS feature enables requires libcap-ng-devel as
prerequisite for build to be successful otherwise following error is
seen on Ubuntu 20.04:
../meson.build:1075:6: ERROR: Problem encountered: virtio-9p (virtfs) requires libcap-ng-devel and libattr-devel
Fix this via adding corresponding prerequisite.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
=> building: prerequisite: add libcap-ng-dev

architecture/arm_security_extensions.rst, faq/faq.rst
Explain how to easily build a GCC toolchain compatible with OP-TEE's
CFG_CORE_BTI=y/CFG_TA_BTI=y.
=> faq: Add a question for building GCC with BTI

architecture/crypto.rst
Initial introduction to crypto IC and the API.
The documentation should grow with dedicated sections to each IC.
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
=> crypto: introduce references to crypto IC

architecture/core.rst
Should be TTBCR (Translation Table Base Control Register).
Signed-off-by: Ding Tao <miyatsu@qq.com>
=> architecture: core: Fix simple typo by replace TTBRC with TTBCR

debug/benchmark.rst
The kernel patch required by the benchmark framework is not maintained
in the linaro-swg/linux Git anymore. Add a note to the documentation.
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
=> benchmark: add a note about the required kernel patch

architecture/secure_storage.rst
Some platforms now do support retrieval of the Hardware Unique Key and/or
Chip ID, update this warning for the same.
Signed-off-by: Andrew Davis <afd@ti.com>
=> Secure storage HUK warning update

architecture/porting_guidelines.rst
For vendors porting their RNG drivers to OP-TEE, it is important that
both `hw_get_random_byte()` and `crypto_rng_read()` should be overriden for
optimal performance if the hardware entropy source supports getting
multiple bytes at a time.
=> architecture: porting_guidelines: Expand section about RNG

general/platforms.rst
Add the AMD/Xilinx Versal Adaptive Compute Acceleration Platform
Reference board:
https://www.xilinx.com/products/boards-and-kits/vck190.html
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
=> platform: add AMD/Xilinx Versal ACAP

building/devices/versal.rst
Changed Xilinx to AMD-Xilinx. Added information about the VMK180 board and added information on how to customize the PLM so that the PUF and eFUSEs can be used with this version of OP-TEE.
Signed-off-by: Nathan Menhorn <nathan.menhorn@amd.com>
=> Changed Xilinx to AMD-Xilinx. Added information about the VMK180 board and information about the PLM

building/devices/zynqmp.rst
New PR to update the build documentation for ZynqMP devices. The documentation covers both the current build makefiles as well as the new platforms added in the latest pull request to the build repository (see https://github.com/OP-TEE/build/pull/591).
Previous PR to the doc was closed as it was not supporting all the platforms previously supported (see https://github.com/OP-TEE/optee_docs/pull/141)
=> zynqmp: updated content based on new build makefile

building/prerequisites.rst
Adds libslirp-dev (needed by QEMU 7.1+) to prerequisite host package list.
=> building: prerequisite: add libslirp-dev

building/prerequisites.rst
When building for RockPi4 using Ubuntu 22.04 we need to have the host package 'swig' installed as well.
=> docs: add 'swig' to the Ubuntu 22.04 prerequisites

faq/faq.rst
Adds a section with a link to OP-TEE OS Security Advisories hosted in github where the information is. Updates Riscure mini-audit info to point that URL.
=> faq: add link to optee-os secu advisories

architecture/porting_guidelines.rst
Mention HWRNG PTA service configuration switch added since 3.14.0.
=> architecture: porting_guidelines: mention HWRNG PTA

building/devices/qemu.rst
Using QEemu to debug on branches is a useful feature and possibly not obvious to people not familiar with "repo". People unfamiliar with "make" might not know about parallel builds. Include hints about both.
=> building: qemu: added hints about repo and make

.readthedocs.yaml
readthedocs build have some warning:
- WARNING: plantuml command 'plantuml' cannot be run
- WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
Which means the build system losing the `plantuml` and `graphviz` packages.
Acroording to the [build-apt-packages](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages), we could install some package using the apt.
So, just add the `plantuml` and `graphviz`, readthedocs can build the `uml` succesfully.
The fixed doc with `uml` could see [here](https://optee-docs-test.readthedocs.io/en/latest/architecture/core.html#id11).
=> fix readthedocs build warnings

building/devices/qemu.rst
The repo command fetches code in the current directory so it is best to run it inside a directory created specifically for that purpose.
The mentions about disabling ASLR are not exact (TA ASLR has its own config flag) and are not very relevant to the short descriptions so remove them.
=> building: qemu: update fetch/build/run command example

building/Dockerfile.Ubuntu-20.04, building/Dockerfile.Ubuntu-22.04, building/prerequisites.rst
Instead of providing the list of required packages as an apt command, give a full Dockerfile. The advantage being, it can be used directly to build and therefore make sure the list is still up to date. For example:
$ cd building
$ docker build --no-cache -f Dockerfile.Ubuntu-22.04 .
=> building: prerequisites: provide Dockerfiles

architecture/globalplatform_api.rst
Add a section to help optimizing TEE Shared Memory for better performance using zero-copy.
=> architecture: optimizing TEE Shared Memory

building/devices/stm32mp1.rst
Fix the missing link to the "Get and build the solution" page in the STM32MP1 device documentation.
=> stm32mp1: fix the Get and build the solution link

building/Dockerfile.Ubuntu-20.04, building/Dockerfile.Ubuntu-22.04
When building on Ubuntu 20.04 or 22.04, libcap-ng-dev is needed, not libcap-dev. Without the latter, the QEMU build fails when "make XEN_BOOT=y" is invoked.
=> building: prerequisites: fix Ubuntu Dockerfiles

building/devices/versal.rst
Added PetaLinux instructions on how to build the custom PLM required for the Versal OP-TEE port.
=> Added PetaLinux instructions on how to build the custom PLM

building/aosp/aosp.rst
The AOSP build for OP-TEE hasn't been updated, nor being maintained since July 2021. Update the documentation to make it clear that this is the current state for OP-TEE AOSP builds.
Fixes: https://github.com/linaro-swg/optee_android_manifest/issues/77
=> aosp: add warning about build no longer being maintained

architecture/core.rst
Adds a section in core architecture documentation to describe interrupt controllers API functions.
These commits are based on stalled P-R https://github.com/OP-TEE/optee_docs/pull/192.
The 1st commit describes the API since https://github.com/OP-TEE/optee_os/pull/6354 has been merged.
The 2nd commit is an RFC describing the API as per P-R https://github.com/OP-TEE/optee_os/pull/6361.
=> core: using native interrupt handlers

architecture/libraries.rst, architecture/trusted_applications.rst
Adds a section about libutils. There are often questions on stdlib support in OP-TEE. This section can serve as a reference.
=> architecture: libraries: mention libutils

building/gits/build.rst
Over the years, there has unfortunately been some slowdown when using the repo reference command. We reported this issue [1] and for some time we temporarily checked out an earlier commit as a workaround. However, Google seemed to improved it again in later versions and although slower, it was acceptable.
However, we've noticed that things are running slower yet again. After some trail and error, we've concluded that adding the "--partial-clone" when running the "repo init" command together with "--reference" brings down the sync time to less than a minute again. Therefore from now on we recommend using that when using reference mirrors.
Link: https://issues.gerritcodereview.com/issues/40014651?pli=1 [1]
=> build: add --partial-clone when using --reference

building/trusted_applications.rst
The documentation was partly faulty:
- The private key was specified for the digest and stitch steps
- The Nitro HSM section was not correct and did not execute in the shell
This commit extends the documentation and explicitly sets elfs, digest, signature and .ta locations for completeness. This is needed for automated build environments like Yocto, since it builds TAs in several different recipes.
Fixes https://github.com/OP-TEE/optee_docs/issues/224
=> Offline signing of TAs: Improve the documentation

debug/ftrace.rst
`optee_os/scripts/ftrace_format.py` does not read from `stdin`, hence piping the output of `cat` into it does not work and only prints usage information:
```
Usage: optee_os/scripts/ftrace_format.py ftrace.out
Converts a ftrace file to text. Output is written to stdout.
```
Instead, the `ftrace-<ta_uuid>.out` file has to be given as an argument like shown in the example in [5c2c0fb31efb](https://github.com/OP-TEE/optee_os/commit/5c2c0fb31efb).
```
optee_os/scripts/ftrace_format.py ftrace-<ta_uuid>.out  | optee_os/scripts/symbolize.py -d <ta_uuid>.elf -d tee.elf
```
=> Fix ftrace_format.py not reading from stdin

building/efi_vars/stmm.rst
Hi,
I found a typo in the doc, I think it should be `StandAloneMM` instead of `StandAlomeMM`
=> building: standalonemm: Fix typo for StandAloneMM

architecture/core.rst
Removes non-ASCII characters 0xc2 0xa0 and fix indentation with space chars 0x20 in core native interrupts API function description. Documentation rendering was affected by these characters.
Fixes: eda1e0fd8bb4 ("core: using native interrupt handlers")
=> core: fix bad space char in native interrupt API description

building/trusted_applications.rst
Seems like I overlooked two double quotes
=> Typo quickfix in TA signing section

architecture/spmc.rst, conf.py, requirements.txt
ReadtheDocs now require at least version 5.0 of Sphinx. We've been using 4.5.0 and therefore we needed to upgrade to a more recent version.
Sphinx:
- Upgrade Sphinx to v7.2.6.
- Upgrade all packages and modules needed to the most recent versions as of today.
- Replace 'sphinx_panels' (deprecated) with 'sphinx_design'.
- Sort the packages and modules alphabetically in the requirements.txt file.
Errors:
- When doing the upgrade we got multiple errors from the SPMC pages, it looks like the way to refer to an icon has been changed from 'opticon' to 'octicon'. To avoid the error when upgrading, fix this in the same commit.
=> config: Upgrade Sphinx and dependencies

architecture/device_tree.rst, architecture/device_tree_bindings/google_widevine_bindings.rst, architecture/device_tree_bindings/index.rst, architecture/index.rst
As the suggestion in https://github.com/OP-TEE/optee_os/pull/6418#issuecomment-1794366889, we will move the device tree bindings into the OP-TEE document.
This PR will introduce a new location to place the OP-TEE specific device tree binding yaml files.
=> architecture: Add device tree bindings docs

architecture/crypto.rst
When using FIPS 140-2 certified cryptographip devices, the fact that operating on some unsupported key sizes might fallback to the cipher's software implementation will cause a degradation in the cipher's security level.
Create a note to higlight this fact.
=> crypto: reference to FIPS 140-2 certification

architecture/porting_guidelines.rst
Change the link to point to the correct page when refering to configuration and compile time flags.
Fixes: https://github.com/OP-TEE/optee_docs/issues/142
=> porting guidelines: fix bad link

building/toolchains.rst
The old link was to: https://developer.arm.com/open-source/gnu-toolchain/gnu-a/downloads which says it is "Deprecated"
The new link is to: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
The example wget commands should probably be updated as well, but I'll keep this PR simple.
=> toolchains.rst: Update deprecated download page

architecture/porting_guidelines.rst, building/devices/rpi3.rst
The file has been moved to a `design` subdirectory. Update the path in two places.
=> Fix broken links to auth-framework.rst

building/Dockerfile.Ubuntu-22.04
The GlobalPlatform extended test suite requires Xalan. Add it to the Ubuntu 22.04 build prerequisites.
=> prereqs/ubuntu-22.04: Add Xalan to build prerequisites

building/trusted_applications.rst
Fixes potential future security vulnerabilites by highlighting the importance of verifying expected parameter types in Trusted Applications, as discussed in the GlobalConfusion paper [1] by Marcel Busch et al.
Note that a proposed fix (and a proof of concept using OP-TEE) is suggested in the same paper, which involves requiring TA writers to register expected function parameters. However, this change has not yet been added to any GlobalPlatform specifications (there is a discussion ongoing).
Link: [1] https://hexhive.epfl.ch/publications/files/24SEC4.pdf
=> ta: add warning about TA parameter checking

architecture/core.rst
Adds information about the interrupt API functions to consider when using device tree to describe interrupts.
=> core: native interrupt using DT bindings

architecture/core.rst
The diagram indicates that IRQ/FIQ are unmasked when entering the Trusted OS. This is likely a typo, as the documentation indicates that both blocking and yielding SMCs start with IRQ/FIQs masked, and the code seem to agree as well.
=> architecture: core: fix IRQ/FIQ masked state in diagram

building/Dockerfile.Ubuntu-20.04, building/Dockerfile.Ubuntu-22.04
Given the varying xalan versions and their distinct behavior on different distributions, adopting xsltproc as a replacement offers consistent multi-distro support, as it appears to be compatible with most platforms.
I haven't tested the 20.04 Dockerfile, if @jforissier has time and ability to do so, it'd be appreciated.
Related to: https://github.com/OP-TEE/optee_test/pull/761
=> dockerfiles: change from xalan to xsltproc

building/Dockerfile.Ubuntu-22.04
When using the Ubuntu 22.04 Dockerfile found on the prerequisites page, a build error occurs:
found no usable tomli, please install it
make: *** [Makefile:293: /optee/build/../qemu/build/config-host.mak] Error 1
This is caused by a QEMU upgrade. The python3-tomli package needs to be added to the apt install command.
Another error is:
checking whether mknod can create fifo without root privileges... configure: error: in `/optee/out-br/build/host-tar-1.35':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
...so let's set FORCE_UNSAFE_CONFIGURE=1.
Setting -j3 instead of -j2 for "make toolchain" is unrelated but is slightly faster so let's improve that too.
=> dockerfiles: fix build on Ubuntu 22.04

architecture/crypto.rst
Since the OP-TEE driver lacks firmware upgrade support, vulnerabilities found in the SE05x HSM cannot be patched and will remain unaddressed.
=> crypto: se05x, no support for firmware upgrade

building/Dockerfile.Ubuntu-22.04
Running `docker build` on the provided Dockerfile is failing due to a missing dependency, `libgnutls28-dev`. I have added it and also updated the build commands to use `apt-get` instead of `apt`, as it is preferable to use `apt-get` when running in a non-interactive context like `docker build`.
=> Fix failing docker build on Ubuntu 22.04
